# Generated by Django 4.0.2 on 2022-02-28 10:08

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('sdgs', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=17)),
            ],
        ),
    ]
