# Generated by Django 4.0.2 on 2022-03-02 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdg', '0002_sdg'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='sdg_strength',
            field=models.CharField(default='a', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='document',
            name='sdgs',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='document',
            name='url',
            field=models.URLField(max_length=255),
        ),
    ]
