# Generated by Django 4.0.2 on 2022-03-02 09:35

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('sdg', '0003_document_sdg_strength_alter_document_sdgs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='sdg_strength',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=17),
        ),
        migrations.AlterField(
            model_name='document',
            name='sdgs',
            field=models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')]),
        ),
    ]
