# Generated by Django 4.0.2 on 2022-03-02 10:45

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('sdg', '0004_alter_document_sdg_strength_alter_document_sdgs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='sdg_strength',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='document',
            name='sdgs',
            field=models.CharField(max_length=33, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')]),
        ),
    ]
