# Generated by Django 4.0.2 on 2022-03-15 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sdg', '0005_alter_document_sdg_strength_alter_document_sdgs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='sdg_strength',
            field=models.CharField(max_length=33),
        ),
        migrations.CreateModel(
            name='SDGCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('count', models.IntegerField()),
                ('sdg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sdg.sdg')),
            ],
        ),
    ]
