# Generated by Django 4.0.2 on 2022-03-23 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdg', '0007_delete_sdgcount'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='sdg1',
            field=models.CharField(default=0, max_length=2500),
        ),
        migrations.AddField(
            model_name='document',
            name='sdg10',
            field=models.CharField(default=0, max_length=2500),
        ),
        migrations.AddField(
            model_name='document',
            name='sdg11',
            field=models.CharField(default=0, max_length=2500),
        ),
        migrations.AddField(
            model_name='document',
            name='sdg12',
            field=models.CharField(default=0, max_length=2500),
        ),
        migrations.AddField(
            model_name='document',
            name='sdg13',
            field=models.CharField(default=0, max_length=2500),
        ),
        migrations.AddField(
            model_name='document',
            name='sdg14',
            field=models.CharField(default=0, max_length=2500),
        ),
        migrations.AddField(
            model_name='document',
            name='sdg15',
            field=models.CharField(default=0, max_length=2500),
        ),
        migrations.AddField(
            model_name='document',
            name='sdg16',
            field=models.CharField(default=0, max_length=2500),
        ),
        migrations.AddField(
            model_name='document',
            name='sdg17',
            field=models.CharField(default=0, max_length=2500),
        ),
        migrations.AddField(
            model_name='document',
            name='sdg2',
            field=models.CharField(default=0, max_length=2500),
        ),
        migrations.AddField(
            model_name='document',
            name='sdg3',
            field=models.CharField(default=0, max_length=2500),
        ),
        migrations.AddField(
            model_name='document',
            name='sdg4',
            field=models.CharField(default=0, max_length=2500),
        ),
        migrations.AddField(
            model_name='document',
            name='sdg5',
            field=models.CharField(default=0, max_length=2500),
        ),
        migrations.AddField(
            model_name='document',
            name='sdg6',
            field=models.CharField(default=0, max_length=2500),
        ),
        migrations.AddField(
            model_name='document',
            name='sdg7',
            field=models.CharField(default=0, max_length=2500),
        ),
        migrations.AddField(
            model_name='document',
            name='sdg8',
            field=models.CharField(default=0, max_length=2500),
        ),
        migrations.AddField(
            model_name='document',
            name='sdg9',
            field=models.CharField(default=0, max_length=2500),
        ),
    ]
